# Generated by Django 3.0.4 on 2020-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagesettings',
            name='site_title',
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='site_intro_text2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='site_intro_text1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
