# Generated by Django 3.0.4 on 2020-03-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200312_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image1', models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d')),
                ('gallery_image2', models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d')),
                ('gallery_image3', models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d')),
                ('gallery_image4', models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d')),
                ('gallery_image5', models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d')),
                ('gallery_image6', models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d')),
            ],
        ),
        migrations.AlterModelOptions(
            name='homepagesettings',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='site_intro_heading',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='settings_name',
            field=models.CharField(blank=True, default='Settings', max_length=30),
        ),
    ]
