# Generated by Django 3.0.4 on 2020-03-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200312_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_image6',
        ),
    ]
