# Generated by Django 3.0.4 on 2020-03-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200313_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
