# Generated by Django 3.0.4 on 2020-03-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200313_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(blank=True, default='Gallery Settings', max_length=50),
        ),
    ]
