# Generated by Django 3.0.4 on 2020-03-13 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_gallery_gallery_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagesettings',
            options={'ordering': ['-pk'], 'verbose_name': 'Home Page Setting', 'verbose_name_plural': 'Home Page Settings'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_image5',
        ),
    ]
