# Generated by Django 3.0.4 on 2020-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200313_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image1',
            field=models.ImageField(upload_to='blog_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image2',
            field=models.ImageField(upload_to='blog_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image3',
            field=models.ImageField(upload_to='blog_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image4',
            field=models.ImageField(upload_to='blog_pics/%Y/%m/%d'),
        ),
    ]
