# Generated by Django 3.0.4 on 2020-03-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200313_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image1',
            field=models.ImageField(upload_to='site_pics/gallery_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image2',
            field=models.ImageField(upload_to='site_pics/gallery_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image3',
            field=models.ImageField(upload_to='site_pics/gallery_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image4',
            field=models.ImageField(upload_to='site_pics/gallery_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='middle_background_img',
            field=models.ImageField(upload_to='site_pics/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='top_background_img',
            field=models.ImageField(upload_to='site_pics/%Y/%m/%d'),
        ),
    ]
