# Generated by Django 3.0.4 on 2020-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200314_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
