# Generated by Django 3.0.4 on 2020-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='Uncategorised', max_length=80, unique=True),
        ),
    ]
