# Generated by Django 3.0.4 on 2020-03-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostView',
        ),
    ]
