# Generated by Django 3.0.4 on 2020-03-07 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_like_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_content',
            field=ckeditor.fields.RichTextField(default='test'),
            preserve_default=False,
        ),
    ]
