# Generated by Django 3.0.4 on 2020-03-11 12:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('blog', '0007_post_main_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(help_text='Multiple categories can be selected.', to='categories.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_content',
            field=ckeditor.fields.RichTextField(verbose_name='main_content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(help_text='comment or the overview of the post.', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.TextField(help_text='Title of your post.', verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d', verbose_name='thumbnail'),
        ),
    ]
