# Generated by Django 3.0.4 on 2020-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('blog', '0008_auto_20200311_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='categories.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.TextField(verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog_pics/%Y/%m/%d'),
        ),
    ]
