# Generated by Django 3.0.4 on 2020-03-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200314_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pics/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
