# Generated by Django 3.0.4 on 2020-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200314_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', upload_to='blog_pics/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
