# Generated by Django 3.0.4 on 2020-04-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200330_1002'),
        ('blog', '0019_auto_20200330_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='categories.Category'),
        ),
    ]
