# Generated by Django 3.0.4 on 2020-04-02 02:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200401_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
