# Generated by Django 3.0.4 on 2020-05-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200507_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
