# Generated by Django 3.0.4 on 2020-05-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_tagname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tagname',
            field=models.TextField(default='', max_length=50),
        ),
    ]
